**assistant**:
> Below are selected log entries of past conversations, as part of an experimental AI memory system. They may have no bearing on the chat.
> 
> 
>   2022-12-24:
>   How to convert the type of a tibble column from chr to dbl; `as.double()` function for single or multiple columns.
> 
> 
> 
>   2023-03-11:
>   Explained broadcasting NaN issue in xarray and provided method to create DataArray from DataSet dimensions; answered how to subset columns and get column list in GeoPandas.
> 
> 
> 
>   2023-07-26:
>   Fixing orphaned hole error in shapefile; Converting gBuffer output to SpatialPoly for writing.
> 
> 
> 
>   2023-08-29:
>   Improving Color Visibility in ggplot2 Legends
> 
> 
> 
>   2023-09-22:
>   Including Geoms in ggplot Legends without Plotting
> 
> 
> 
>   2023-08-18:
>   How to label features in QGIS using field values; Achieving automatic label placement for visibility.
> 
> 
> 
>   2023-08-19:
>   Quick Retrieval of Last N Lines from a File in Python
> 
> 
> 
>   2023-10-02:
>   Creating Julia Matrices with Zeros and Missing Values
> 
> 
> 
>   2023-09-19:
>   Including Values in ggplot Legend
> 
> 
> 
>   2023-09-22:
>   Adding Legend Entry without Drawing Geom in ggplot
> 
> 
>     
**user**:
> I am plotting a map in ggplot. When I do this without `coord_map(ylim=c(-50, 65))` it works fine and fairly fast. When I add this line in though, I get the error:
> ```Error in vapply(X, FUN, FUN.VALUE = character(1), ..., USE.NAMES = USE.NAMES) : 
>   values must be type 'character',
>  but FUN(X[[1]]) result is type 'list'```
> 
> How can I fix this?
**assistant**:
> The error suggests that one of the functions being used in the pipeline is expecting character type inputs, but it is facing a list type value instead. 
> 
> Given that you are using `ggplot2` and the error seems to occur when you insert a coordinate specification, it might be that the character-to-list conflict is due to the wrong data type fed into the `ylim` argument in `coord_map`.
> 
> Can you double check that both `-50` and `65` are of 'numeric' type and not a list or a data frame? Here's how you can check:
> 
> ```r
> is.numeric(-50)       # Should return TRUE
> is.numeric(65)        # Should return TRUE
> ```
> 
> If the condition returns `TRUE` for both, verify that you're using the latest version of `ggplot2` because sometimes this error arises due to a bug that was fixed in a newer version. If not, please update `ggplot2` using:
> 
> ```r
> install.packages('ggplot2')
> ```
> 
> Also make sure that your dataset does not contain any incompatible datatypes with the mapping aesthetics used in your plot.
> 
> Try running the plot without `coord_map()`, then adding the `ylim` within a new `coord_cartesian()` line like so:
> 
> ```r
> # Replace "dat" and "mapping_aesthetics" with your data and mappings
> ggplot(data = dat, mapping = aes(mapping_aesthetics)) +
>   geom_map() +
>   coord_cartesian(ylim = c(-50, 65))
> ```
> 
> Please provide me with the output and we can continue from there.
